version: '3'

services:
  master1:
    image: cluster
    container_name: master1
    hostname: master1
    command: /scripts/master1.sh
    depends_on:
      - slave1
      - slave2
      - slave3
      - master2
      - master3
    ports:
      - 221:22
      - 50070:50070
      - 8088:8088
      - 19888:19888
      - 8042:8042
      - 18080:18080
    networks:
      - my_cluster

  master2:
    image: cluster
    container_name: master2
    hostname: master2
    command: /scripts/master2.sh
    depends_on:
      - master3
    ports:
      - 222:22
      - 50071:50070
      - 8089:8088
      - 19889:19888
      - 8043:8042
      - 18081:18080
    networks:
      - my_cluster

  master3:
    image: cluster
    container_name: master3
    hostname: master3
    command: /scripts/master3.sh
    ports:
      - 223:22
      - 50072:50070
      - 8098:8088
      - 19898:19888
      - 8044:8042
    networks:
      - my_cluster

  slave1:
    image: cluster
    container_name: slave1
    hostname: slave1
    ports:
      - 224:22
    networks:
      - my_cluster

  slave2:
    image: cluster
    container_name: slave2
    hostname: slave2
    ports:
      - 225:22
    networks:
      - my_cluster

  slave3:
    image: cluster
    container_name: slave3
    hostname: slave3
    ports:
      - 226:22
    networks:
      - my_cluster

networks:
  my_cluster:
